name: ✅️ Test

on: [push, pull_request]

jobs:
  install:
    name: Install (Ubuntu) 📌
    runs-on: ubuntu-latest
    steps:
      - name: Clone 👀
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install 📌
        run: make install

  test:
    name: Test (Ubuntu) 🎯
    runs-on: ubuntu-latest
    steps:
      - name: Clone 👀
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install 📌
        run: make develop

      - name: Test 🎯
        run: make test
